### ISSUE TITLE
Solr timeout?

### ISSUE THREAD

**Issue by ajs6f** [ckan/ckan-docker#106]
I'm seeing repeated errors of the following kind in the logs for my `ckan` container. You may notice that I have already "upped" my ` ckan.requests.timeout` parameter to 15. This is because (as shown below the error in question) I am operating this gear on a small VM and it takes about 8 seconds for `solr` to return a schema. (Or to respond to pretty much any other query.) So the request should not time out, and there is clearly fine connectivity from container `ckan` to container `solr` (hence the successful timed `curl` request). Any thoughts on why it is timing out from the initialization of search?

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='solr', port=8983): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/app/wsgi.py", line 20, in <module>
    application = make_app(config)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 220, in load_all
    unload_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 270, in unload_all
    unload(*reversed(_PLUGINS))
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 302, in unload
    plugins_update()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 212, in plugins_update
    environment.update_config()
  File "/srv/app/src/ckan/ckan/config/environment.py", line 184, in update_config
    search.check_solr_schema_version()
  File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 366, in check_solr_schema_version
    res = _get_schema_from_solr(SOLR_SCHEMA_FILE_OFFSET_MANAGED)
  File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 322, in _get_schema_from_solr
    response = requests.get(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='solr', port=8983): Read timed out. (read timeout=15)
unable to load app 0 (mountpoint='') (callable not found or import error)
```

```
249129d856ba:/srv/app# time curl -s http://solr:8983/solr/ckan/schema 1>/dev/null

real	0m8.010s
user	0m0.001s
sys	0m0.002s
```

**Comment by ajs6f** [comment]
I have changed the timeout value to 50, and this error went away, so that I think now that I simply have a very, very slow setup. :) Sorry for the confusion!
