### ISSUE TITLE
Cannot import name 'relation' from 'sqlalchemy.orm

### ISSUE THREAD

**Issue by anonpython1** [ckan/ckan-docker#166]
```
ckan-dev_1    | Traceback (most recent call last):
ckan-dev_1    |   File "/usr/bin/ckan", line 5, in <module>
ckan-dev_1    |     from ckan.cli.cli import ckan
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/cli/cli.py", line 12, in <module>
ckan-dev_1    |     import ckan.plugins as p
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/plugins/__init__.py", line 3, in <module>
ckan-dev_1    |     from ckan.plugins.core import *  # noqa: re-export
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 21, in <module>
ckan-dev_1    |     import ckan.plugins.interfaces as interfaces
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/plugins/interfaces.py", line 17, in <module>
ckan-dev_1    |     from ckan.model.user import User
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/model/__init__.py", line 31, in <module>
ckan-dev_1    |     from ckan.model.package import (
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/model/package.py", line 492, in <module>
ckan-dev_1    |     from ckan.model import tag
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/model/tag.py", line 6, in <module>
ckan-dev_1    |     from sqlalchemy.orm import relation
ckan-dev_1    | ImportError: cannot import name 'relation' from 'sqlalchemy.orm' (/usr/lib/python3.10/site-packages/sqlalchemy/orm/__init__.py)
ckan-dev_1    | Exit with status 1. Restarting.
```

Getting this error. on running `docker-compose -f docker-compose.dev.yml up`. Any solution?

**Comment by kowh-ai** [comment]
@anonpython1 - have you changed the `FROM ckan/ckan-dev:2.10.4` line in Dockerfile.dev. I just need to know what to test this issue with

**Comment by anonpython1** [comment]
@kowh-ai  Nope,  i didn't change anything in Dockerfile.dev file.

**Comment by kowh-ai** [comment]
For me it works....This is odd as `relation` changed to `relationship` from sqlalchemy v**0.6** 

I'd clean your whole docker environment and start again, please see: https://github.com/ckan/ckan-docker/wiki/Docker-cleanup
