### ISSUE TITLE
Plugin datapusher cannot be loaded

### ISSUE THREAD

**Issue by tigrouxyz** [ckan/ckan-docker#170]
I have a problem with Datapusher and latest version of CKAN 2.11

- Checked out https://github.com/ckan/ckan-docker/
- copied .env.example to .env
- docker compose build
- docker compose up

I get the following logs on CKAN

```
2024-09-03 21:33:15 Traceback (most recent call last):
2024-09-03 21:33:15   File "/srv/app/prerun.py", line 214, in <module>
2024-09-03 21:33:08 Setting a temporary value for ckan.datapusher.api_token
2024-09-03 21:33:09 Setting SECRET_KEY in ini file
2024-09-03 21:33:15 [prerun] Initializing or upgrading db - start
2024-09-03 21:33:15 Command '['ckan', '-c', '/srv/app/ckan.ini', 'db', 'init']' returned non-zero exit status 1.
2024-09-03 21:33:15 b"2024-09-03 19:33:13,865 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini\n2024-09-03 19:33:13,866 INFO  [ckan.config.environment] Loading static files from public\n2024-09-03 19:33:14,498 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates\n2024-09-03 19:33:14,774 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.\n2024-09-03 19:33:14,945 INFO  [ckan.model] CKAN database version remains as: 4a5e3465beb6 (head)\nPlugin 'datapusher' cannot be loaded.\nAborted!\n"
2024-09-03 21:33:15 /srv/app/start_ckan.sh: Running init file /docker-entrypoint.d/01_setup_datapusher.sh
2024-09-03 21:33:15 Set up ckan.datapusher.api_token in the CKAN config file
2024-09-03 21:33:18 /srv/app/start_ckan.sh: Ignoring /docker-entrypoint.d/README.md (not an sh or py file)
2024-09-03 21:33:18 2024-09-03 19:33:18,212 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-09-03 21:33:18 2024-09-03 19:33:18,212 WARN No file matches via include "/etc/supervisord.d/*.conf"
2024-09-03 21:33:18 2024-09-03 19:33:18,217 INFO RPC interface 'supervisor' initialized
2024-09-03 21:33:18 2024-09-03 19:33:18,217 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-09-03 21:33:18 2024-09-03 19:33:18,218 INFO supervisord started with pid 39
2024-09-03 21:33:15     init_db()
2024-09-03 21:33:15   File "/srv/app/prerun.py", line 112, in init_db
2024-09-03 21:33:15     raise e
2024-09-03 21:33:15   File "/srv/app/prerun.py", line 102, in init_db
2024-09-03 21:33:15     subprocess.check_output(db_command, stderr=subprocess.STDOUT)
2024-09-03 21:33:15   File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
2024-09-03 21:33:15     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
2024-09-03 21:33:15   File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
2024-09-03 21:33:15     raise CalledProcessError(retcode, process.args,
2024-09-03 21:33:15 subprocess.CalledProcessError: Command '['ckan', '-c', '/srv/app/ckan.ini', 'db', 'init']' returned non-zero exit status 1.
2024-09-03 21:33:16 2024-09-03 19:33:16,012 INFO  [ckan.cli] Using configuration file /srv/app/ckan.ini
2024-09-03 21:33:16 2024-09-03 19:33:16,012 INFO  [ckan.config.environment] Loading static files from public
2024-09-03 21:33:16 2024-09-03 19:33:16,469 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-09-03 21:33:16 2024-09-03 19:33:16,689 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-09-03 21:33:16 User not found
2024-09-03 21:33:16 Aborted!
2024-09-03 21:33:18 open("./http_plugin.so"): No such file or directory [core/utils.c line 3709]
2024-09-03 21:33:18 !!! UNABLE to load uWSGI plugin: ./http_plugin.so: cannot open shared object file: No such file or directory !!!
2024-09-03 21:33:18 open("./python_plugin.so"): No such file or directory [core/utils.c line 3709]
2024-09-03 21:33:18 !!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
2024-09-03 21:33:18 *** Starting uWSGI 2.0.26 (64bit) on [Tue Sep  3 19:33:18 2024] ***
2024-09-03 21:33:18 compiled with version: 12.2.0 on 22 August 2024 12:27:29
2024-09-03 21:33:18 os: Linux-5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024
2024-09-03 21:33:18 nodename: 49bbfbde42c9
2024-09-03 21:33:18 machine: x86_64
2024-09-03 21:33:18 clock source: unix
2024-09-03 21:33:18 detected number of CPU cores: 16
2024-09-03 21:33:18 current working directory: /srv/app
2024-09-03 21:33:18 detected binary path: /usr/local/bin/uwsgi
2024-09-03 21:33:18 !!! no internal routing support, rebuild with pcre support !!!
2024-09-03 21:33:18 uWSGI running as root, you can use --uid/--gid/--chroot options
2024-09-03 21:33:18 setgid() to 92
2024-09-03 21:33:18 setuid() to 92
2024-09-03 21:33:18 your memory page size is 4096 bytes
2024-09-03 21:33:18  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
2024-09-03 21:33:18 detected max file descriptor number: 1048576
2024-09-03 21:33:18 lock engine: pthread robust mutexes
2024-09-03 21:33:18 thunder lock: disabled (you can enable it with --thunder-lock)
2024-09-03 21:33:18 uWSGI http bound on [::]:5000 fd 3
2024-09-03 21:33:18 uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 6
2024-09-03 21:33:18 Python version: 3.10.14 (main, Aug 13 2024, 01:17:25) [GCC 12.2.0]
2024-09-03 21:33:18 Python main interpreter initialized at 0x559d3bcda460
2024-09-03 21:33:18 python threads support enabled
2024-09-03 21:33:18 your server socket listen backlog is limited to 100 connections
2024-09-03 21:33:18 your mercy for graceful operations on workers is 60 seconds
2024-09-03 21:33:18 mapped 304776 bytes (297 KB) for 2 cores
2024-09-03 21:33:18 *** Operational MODE: preforking ***
2024-09-03 21:33:18 *** uWSGI is running in multiple interpreter mode ***
2024-09-03 21:33:18 spawned uWSGI master process (pid: 40)
2024-09-03 21:33:18 spawned uWSGI worker 1 (pid: 41, cores: 1)
2024-09-03 21:33:18 spawned uWSGI worker 2 (pid: 42, cores: 1)
2024-09-03 21:33:18 spawned uWSGI http 1 (pid: 43)
2024-09-03 21:33:18 2024-09-03 19:33:18,913 INFO  [ckan.config.environment] Loading static files from public
2024-09-03 21:33:18 2024-09-03 19:33:18,931 INFO  [ckan.config.environment] Loading static files from public
2024-09-03 21:33:19 2024-09-03 19:33:19,507 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-09-03 21:33:19 2024-09-03 19:33:19,507 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-09-03 21:33:19 2024-09-03 19:33:19,660 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-09-03 21:33:19 2024-09-03 19:33:19,661 WARNI [ckan.config.middleware.flask_app] Extensions are excluded from CSRF protection! We allow extensions to run without CSRF protection but it will be forced future releases. Read the documentation for more information on how to add CSRF protection to your extension.
2024-09-03 21:33:19 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x559d3bcda460 pid: 42 (default app)
2024-09-03 21:33:19 mountpoint  already configured. skip.
2024-09-03 21:33:19 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x559d3bcda460 pid: 41 (default app)
2024-09-03 21:33:19 mountpoint  already configured. skip.
2024-09-03 21:34:08 2024-09-03 19:34:08,765 WARNI [ckan.common] Option lang is not declared
2024-09-03 21:34:09 2024-09-03 19:34:09,345 INFO  [ckan.config.middleware.flask_app]  200 / render time 0.564 seconds
```

When I downgrade the image to ckan-base:2.10-py3.10, clean my volumes and restart, it is working without problem.

**Comment by kowh-ai** [comment]
Does the DataPusher container start up? 

There is a problem with setting the Admin user at the moment: https://github.com/ckan/ckan-docker/issues/171

Do you create an Admin user and login?

**Comment by tigrouxyz** [comment]
Yes the Datapusher container starts (I also tried with Datapusher plus with the same result).

`2024-09-04 11:27:48 [uWSGI] getting INI configuration from /srv/app/datapusher-uwsgi.ini
2024-09-04 11:27:48 *** Starting uWSGI 2.0.19.1 (64bit) on [Wed Sep  4 09:27:48 2024] ***
2024-09-04 11:27:48 compiled with version: 10.3.1 20210424 on 05 April 2021 18:18:03
2024-09-04 11:27:48 os: Linux-5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024
2024-09-04 11:27:48 nodename: 4046aeb8c0d1
2024-09-04 11:27:48 machine: x86_64
2024-09-04 11:27:48 clock source: unix
2024-09-04 11:27:48 pcre jit disabled
2024-09-04 11:27:48 detected number of CPU cores: 16
2024-09-04 11:27:48 current working directory: /srv/app
2024-09-04 11:27:48 writing pidfile to /tmp/datapusher-uwsgi.pid
2024-09-04 11:27:48 detected binary path: /usr/sbin/uwsgi
2024-09-04 11:27:48 your memory page size is 4096 bytes
2024-09-04 11:27:48  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
2024-09-04 11:27:48 detected max file descriptor number: 1048576
2024-09-04 11:27:48 lock engine: pthread robust mutexes
2024-09-04 11:27:48 thunder lock: disabled (you can enable it with --thunder-lock)
2024-09-04 11:27:48 uWSGI http bound on 0.0.0.0:8800 fd 3
2024-09-04 11:27:48 uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 6
2024-09-04 11:27:48 Python version: 3.9.16 (main, Dec 10 2022, 13:47:19)  [GCC 10.3.1 20210424]
2024-09-04 11:27:48 Python main interpreter initialized at 0x7fc7b492cc00
2024-09-04 11:27:48 python threads support enabled
2024-09-04 11:27:48 your server socket listen backlog is limited to 100 connections
2024-09-04 11:27:48 your mercy for graceful operations on workers is 60 seconds
2024-09-04 11:27:48 mapped 203184 bytes (198 KB) for 1 cores
2024-09-04 11:27:48 *** Operational MODE: single process ***
2024-09-04 11:27:48 /usr/lib/python3.9/site-packages/tzlocal/unix.py:183: UserWarning: Can not find any timezone configuration, defaulting to UTC.
2024-09-04 11:27:48   warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2024-09-04 11:27:48 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7fc7b492cc00 pid: 1 (default app)
2024-09-04 11:27:48 *** uWSGI is running in multiple interpreter mode ***
2024-09-04 11:27:48 spawned uWSGI master process (pid: 1)
2024-09-04 11:27:48 spawned uWSGI worker 1 (pid: 10, cores: 1)
2024-09-04 11:27:48 spawned uWSGI http 1 (pid: 11)`

I did create an admin user and was able to log in to CKAN and create org and dataset. I just not have access to the datapusher tab.

**Comment by amercader** [comment]
The issue should now be fixed in the upstream image. So to get it locally, pull and re-build the images:

```
docker pull ckan/ckan-base:2.11.0
docker compose build ckan
```

If using the dev images:

```
docker pull ckan/ckan-dev:2.11.0
docker compose -f docker-compose.dev.yml build ckan-dev
```

You'll need to stop/remove the current `ckan` / `ckan-dev` containers to use the new ones with the latest image.

**Comment by tigrouxyz** [comment]
It works !
Thanks for the fix.
