### ISSUE TITLE
After Installation, Data Store is not available, table view is not available

### ISSUE THREAD

**Issue by JasonPad19** [ckan/ckan-docker#173]
After a brand-new docker installation, I can successfuly login to site and upload dataset.

But after upload a csv file, DataStore shows error
- Error: Process completed but unable to post to result_url

![image](https://github.com/user-attachments/assets/4cd7bb15-1072-4fe8-a186-3a07ad42bb69)

Also tableview is not available.

![image](https://github.com/user-attachments/assets/21cc4680-2600-4deb-a9ef-ed6f2be8b2c2)

Do you have any idea what I miss please? how to fix it?

**Comment by JasonPad19** [comment]
Found this log in datapusher.

2024-09-22 21:28:15,789 INFO Fetching from: http://ckan:5000/dataset/50a684d5-a158-4a84-9b26-b6f2ab54e50a/resource/06ece1f8-21c2-4c6b-b5b8-7eadd98389ea/download/sp500-index-price.csv
2024-09-23 09:28:16 2024-09-22 21:28:16,049 INFO Determined headers and types: [{'id': 'Date', 'type': 'timestamp'}, {'id': 'PX_LAST', 'type': 'numeric'}]
2024-09-23 09:28:16 2024-09-22 21:28:16,119 INFO Saving chunk 0 
2024-09-23 09:28:16 2024-09-22 21:28:16,157 ERROR Job "push_to_datastore (trigger: date[2024-09-22 21:28:15 UTC], next run at: 2024-09-22 21:28:15 UTC)" raised an exception
2024-09-23 09:28:16 Traceback (most recent call last):
2024-09-23 09:28:16   File "/usr/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2024-09-23 09:28:16     retval = job.func(*job.args, **job.kwargs)
2024-09-23 09:28:16   File "/usr/lib/python3.9/site-packages/datapusher-0.0.20-py3.9.egg/datapusher/jobs.py", line 527, in push_to_datastore
2024-09-23 09:28:16     send_resource_to_datastore(resource, headers_dicts, records,
2024-09-23 09:28:16   File "/usr/lib/python3.9/site-packages/datapusher-0.0.20-py3.9.egg/datapusher/jobs.py", line 259, in send_resource_to_datastore
2024-09-23 09:28:16     check_response(r, url, 'CKAN DataStore')
2024-09-23 09:28:16   File "/usr/lib/python3.9/site-packages/datapusher-0.0.20-py3.9.egg/datapusher/jobs.py", line 156, in check_response
2024-09-23 09:28:16     raise HTTPError(
2024-09-23 09:28:16 datapusher.jobs.HTTPError: <unprintable HTTPError object>

**Comment by JasonPad19** [comment]
Hi @kowh-ai , No I didn't change any configuration in Dockerfile

**Comment by asayee0** [comment]
Were you ever able to solve this problem? I am having the same issue on both local and reverse proxying to my work server.

A couple things that I found:
- Adding `resouce_proxy` to the plugins did not work, as was suggested in the [configuration docs](https://docs.ckan.org/en/latest/maintaining/data-viewer.html#resource-proxy)
- Setting the `DATAPUSHER_VERSION` variable in the .env to 0.0.21 instead of the default 0.0.20 didn't work either
- I previously had CORS errors showing in my browser window, and I noticed that my `ckan.site_url` value in the container did not match the `CKAN_SITE_URL` that i set in my .env. I fixed that issue, but it did not help to show any more resource views.
- When the error for Datastore shows, "Error: Process completed but unable to post to result_url", I am still able to click the Upload button and it seems to work just fine. But after that, when I click delete, it returns an error.
- The master branch of this repo currently has the `CKAN_VERSION` set to 2.10.0, instead of 2.11 in the Dockerfile.
- [This discussion](https://github.com/ckan/ckan/discussions/7412) in the main repo seems to be the same problem, but the suggestion of placing "https" in ckan.site_url in `ckan.ini` has not worked for me. In here also, someone suggested dropping the CKAN version down to 2.9.8 makes it work, however this did not work for me.

I kinda feel like I'm grasping at straws at this point, but those are the notes I thought might be related to the issue. The only other thing that I can think of is that, my work server requires the app to be run on http so that it can reverse proxy to https. I'm wondering if, because the app is being served on http locally, it causes problems somehow.

**Comment by ekoilkom** [comment]
I encountered an issue when the default contents of .env are changed, especially when the user password is modified.
If using the default environment variables, the DataPusher process runs smoothly.
