### ISSUE TITLE
installation issues  Exception: Config option `ckan.datapusher.api_token` must be set to use the DataPusher.

### ISSUE THREAD

**Issue by ken-muturi** [ckan/ckan-docker#78]
i get the below errors even after running

`docker stop $(docker ps -q); docker rm $(docker ps -aq); docker image rm $(docker image ls -q); docker network rm $(docker network ls -q); docker volume rm $(docker volume ls -q)` followed by `docker system prune `

then

```
docker compose build
docker compose up
```

```
 09:16:00,457 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
ckan        | Traceback (most recent call last):
ckan        |   File "/srv/app/wsgi.py", line 20, in <module>
ckan        |     application = make_app(config)
ckan        |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
ckan        |     load_environment(conf)
ckan        |   File "/srv/app/src/ckan/ckan/config/environment.py", line 69, in load_environment
ckan        |     p.load_all()
ckan        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 224, in load_all
ckan        |     load(*plugins)
ckan        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 255, in load
ckan        |     plugins_update()
ckan        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 212, in plugins_update
ckan        |     environment.update_config()
ckan        |   File "/srv/app/src/ckan/ckan/config/environment.py", line 227, in update_config
ckan        |     plugin.configure(config)
ckan        |   File "/srv/app/src/ckan/ckanext/datapusher/plugin.py", line 52, in configure
ckan        |     raise Exception(
ckan        | Exception: Config option `ckan.datapusher.api_token` must be set to use the DataPusher.
```

**Comment by kowh-ai** [comment]
When the CKAN container comes up do you see the line: "`Set up ckan.datapusher.api_token in the CKAN config file`"
ie:
![Screenshot 2023-08-23 at 3 18 02 pm](https://github.com/ckan/ckan-docker/assets/54408245/ceee926d-316b-4e48-a283-6791a91af48a)
plus do you see the ckan.datapusher.api_token line in the `ckan.ini` file in the running CKAN container?
![Screenshot 2023-08-23 at 3 22 02 pm](https://github.com/ckan/ckan-docker/assets/54408245/5cdf1cc9-81e4-492e-a5ec-2bc2e5cff9ef)

**Comment by ken-muturi** [comment]
i didnt see this Set up ckan.datapusher.api_token in the CKAN config file on the console;

The api token in the container is also empty
![image](https://github.com/ckan/ckan-docker/assets/3158605/4108a3da-54d3-4a56-880a-ace3afc66781)

**Comment by ken-muturi** [comment]
any feedback on this; even cloning a new repo gives me the same message

**Comment by ken-muturi** [comment]
i am still struggling with this issue even after about 10-15 trials;  I even rebuilt my server to ensure i have a clean slate; Is there a way to generate the API token manually?

![image](https://github.com/ckan/ckan-docker/assets/3158605/c38ca8a4-3b06-47b8-b5ee-72907e6cc330)

**Comment by kowh-ai** [comment]
I think you might want to start debugging where the `ckan.datapusher.api_token` gets created and subsequently changed. Take a look  [here](https://github.com/ckan/ckan-docker#5-ckan-images) to understand how to override the setup files for the local image/container

**Comment by ken-muturi** [comment]
thanks, let me look into it

**Comment by kowh-ai** [comment]
Are you using the [master](https://github.com/ckan/ckan-docker/tree/master) branch?

**Comment by ken-muturi** [comment]
I have come back to this with clean os install; i cant seem to get this up;  now i having a loop of  this when i run `docker compose up `![image](https://github.com/ckan/ckan-docker/assets/3158605/a60adde4-c4e1-449d-92e0-eec49c603702)

**Comment by cicerobcastro** [comment]
Hi everyone,

I'm facing the same problem using the Master branch of ckan-docker. 

But this happens when I try to build another image including an extension.

![image](https://github.com/ckan/ckan-docker/assets/2636011/bd72e679-e22c-4de7-a9fb-d0537b10a4bc)

**Comment by ken-muturi** [comment]
i managed to have this install only with the default settings.  I think the only thing i changed was  the db credentials and site url. any other changes would cause this issue.
